### ISSUE TITLE
sample code needed

### ISSUE THREAD

**Issue by gamecubate** [drhayes/impactjs-behaviors#1]
Can you give some sample code for, say, the creation of a behavior such that:
1. entity stands idle for a random amount of time, then
2. entity walks right for a random amount of time, then
3. back to #1

Thanks.

**Comment by drhayes** [comment]
You probably want to look at my EventChain library more than behaviors: https://github.com/drhayes/impactjs-eventchain

Once you're using an event chain to time the events it becomes a lot easier:

```
ig.module(
  'game.behaviors.waitThenRight'
)
.requires(
  'impact.impact',

  'game.behaviors.baseBehavior',
  'game.system.eventChain'
)
.defines(function() {

  WaitThenRight = BaseBehavior.extend({
    name: 'WaitThenRight',

    added: function(entity) {
      this.wait = EventChain(entity)
        .wait(Math.random() * 5)
        .then(function() {
          this.vel.x = 5;
        })
        .wait(Math.random() * 5)
        .then(function() {
          this.vel.x = 0;
        })
        .repeat();
    }

    update: function(entity) {
      this.wait();
    }
  });
});
```

No guarantees this works as is, I didn't test it.

**Comment by gamecubate** [comment]
Thanks for the link. Looking into it now but I have some doubts. The example I provided was probably too simple and gave you the wrong impression. Judging from past readings, it looks like behaviour trees are the best (current) solution for my needs.

I am about to start a coding experiment -- impactjs-driven -- for an ecosystem simulation and need to define agents and their behaviours such that the term "ai" comes to mind. The behaviours in fact will not be simple; various motivators/goals should compete -- ideally fuzzily -- with each other and it should be easy to "rewire" things by simply changing their position in some treelike structure. Hence the BT idea.

I'll look into your code for event-chains, though, just in case. Thanks again.

**Comment by drhayes** [comment]
Okay. Yes, these are not behavior trees in the AI sense. More of a composition-oriented way of decomposing your entities' behaviors and, potentially, re-using them across entities. For example, I had a game that had a `StayOnPlatform` behavior. There was another `FleePlayerWhenHurt` behavior. That kind of thing.

I've got a state machine implementation for Impact as well: https://github.com/drhayes/impactjs-statemachine.

You should probably use this one, though: https://github.com/city41/ImpactPlugins/tree/master/state-machine

**Comment by gamecubate** [comment]
Thanks for that last link. I had read that state machines are less flexible than BTs for game AI (see, among others, http://www.opsive.com/assets/BehaviorDesigner/documentation.php?id=49) . I found just now a BT implementation at http://behavior3.com/ . I'll explore that first. Thanks again.

**Comment by drhayes** [comment]
Thanks for the resources.
